language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.2
  matrix:
    - LUA=lua5.1
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit2.1  # current head of 2.1 branch

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install busted
  - ([ "$LUA" = "lua5.1" ] || [ "$LUA" = "luajit2.1" ]) && luarocks install lapis
  - luarocks make

script: busted
